%run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
%precinctholes('037-los-angeles');
%run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
%precinctholes('059-orange');
%run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
%precinctholes('067-sacramento');
%run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
%precinctholes('071-san-bernardino');
run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
precinctholes('073-san-diego');
run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
precinctholes('075-san-francisco');
run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
precinctholes('079-san-luis-obispo');
run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
precinctholes('081-san-mateo');
run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
precinctholes('085-santa-clara');
run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
precinctholes('097-sonoma');
run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
precinctholes('103-tehama');
run '/u/home/m/mhfeng/matlab_examples/load_javaplex.m';
precinctholes('111-ventura');
